### PR TITLE
Removed Demo gif from README.

### PR DESCRIPTION
**Pull request by hayleycd**
Discussed with @olivekl. The demo gif is not adding value. It is too fast, the type is too small, etc. I am willing to work with folks to add screenshots and text to the README if the team would like to provide users with a taste of what the project is like.

### CODE REVIEW

**Comment by olivekl** [comment]
+1, I agree it would improve the docs to integrate static images where they make sense.

**Comment by oliverchang** [comment]
@jonathanmetzman WDYT?

**Comment by jonathanmetzman** [comment]
The gif is definitely amateurish. I like it though and probably want to replace it with a better gif

**Comment by olivekl** [comment]
How about something that more clearly shows the tool in action? Just a few (slower) frames demonstrating the user inputting commands and then getting results?

**Pull request closed without merging**
